name: build-server
on:
  push:
    branches: [ main, develop ]
jobs:
  docker:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        id: meta
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then echo "TAG=main" >> $GITHUB_OUTPUT; else echo "TAG=develop" >> $GITHUB_OUTPUT; fi
      - uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64
          tags: ghcr.io/ifedayoagboola/bitsgiga-server:${{ steps.meta.outputs.TAG }}
